// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} phone
 * @returns {$CancellablePromise<void>}
 */
export function BlockContact(phone) {
    return $Call.ByID(1360641735, phone);
}

/**
 * @param {string} content
 * @returns {$CancellablePromise<string>}
 */
export function GenerateJsonPrompt(content) {
    return $Call.ByID(1273000323, content);
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetConfig() {
    return $Call.ByID(746850714).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Contact[]>}
 */
export function GetContacts() {
    return $Call.ByID(1515900985).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} phone
 * @returns {$CancellablePromise<$models.Message[]>}
 */
export function GetConversation(phone) {
    return $Call.ByID(2602544107, phone).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetJsonPrompt() {
    return $Call.ByID(1233012980);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GetModels() {
    return $Call.ByID(1227707582).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetPrompt() {
    return $Call.ByID(1795248922);
}

/**
 * @returns {$CancellablePromise<$models.BotStatus>}
 */
export function GetStatus() {
    return $Call.ByID(3870024918).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function GetTotalMessages() {
    return $Call.ByID(1290969578);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function LogoutWhatsApp() {
    return $Call.ByID(3404866084);
}

/**
 * @param {{ [_ in string]?: string }} newCfg
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(newCfg) {
    return $Call.ByID(3901672991, newCfg);
}

/**
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function SaveJsonPrompt(content) {
    return $Call.ByID(1194397977, content);
}

/**
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function SavePrompt(content) {
    return $Call.ByID(3145507875, content);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Start() {
    return $Call.ByID(3304653164);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Stop() {
    return $Call.ByID(2935562056);
}

/**
 * @param {$models.Message[]} history
 * @param {string} message
 * @returns {$CancellablePromise<string>}
 */
export function TestPrompt(history, message) {
    return $Call.ByID(159438018, history, message);
}

/**
 * @param {string} phone
 * @returns {$CancellablePromise<void>}
 */
export function UnblockContact(phone) {
    return $Call.ByID(2637336160, phone);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.Contact.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.Message.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = $models.BotStatus.createFrom;
