// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class BotStatus {
    /**
     * Creates a new BotStatus instance.
     * @param {Partial<BotStatus>} [$$source = {}] - The source object to create the BotStatus.
     */
    constructor($$source = {}) {
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["connected"] = false;
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BotStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BotStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BotStatus(/** @type {Partial<BotStatus>} */($$parsedSource));
    }
}

export class Contact {
    /**
     * Creates a new Contact instance.
     * @param {Partial<Contact>} [$$source = {}] - The source object to create the Contact.
     */
    constructor($$source = {}) {
        if (!("phone" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["phone"] = "";
        }
        if (!("blocked" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["blocked"] = false;
        }
        if (!("last_msg" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_msg"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (!("profile_pic" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["profile_pic"] = "";
        }
        if (!("contact_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["contact_name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Contact instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Contact}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Contact(/** @type {Partial<Contact>} */($$parsedSource));
    }
}

export class Message {
    /**
     * Creates a new Message instance.
     * @param {Partial<Message>} [$$source = {}] - The source object to create the Message.
     */
    constructor($$source = {}) {
        if (!("phone" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["phone"] = "";
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Message}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Message(/** @type {Partial<Message>} */($$parsedSource));
    }
}
