// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as main$0 from "../../../../../message-go/cmd/gui/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "new_msg": main$0.Message;
            "qr_code": string;
            "qr_timeout": boolean;
            "status_change": main$0.BotStatus;
            "sys_log": string;
            "time": string;
            "wa_connected": boolean;
        }
    }
}
