//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as main$0 from "../../../../../message-go/cmd/gui/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "new_msg": $$createType0,
        "status_change": $$createType1,
    }));
}

// Private type creation functions
const $$createType0 = main$0.Message.createFrom;
const $$createType1 = main$0.BotStatus.createFrom;

configure();
